---

- hosts: all
  become: yes
  tasks:
    - name: Update
      command: apt update -y

    - name: install python3
      package:
       name: python3
       state: present
    
    - name: Install docker and some dependencies
      apt:
        name: python3-pip, docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Install docker python module
      pip:
        name: docker
    - name: Download docker image
      docker_image:
              name: httpd
              tag: latest
              source: pull
              # - copy:
              # src: "web.html"
              # dest: "/var/www/html/index.html"
    - name: launnching httpd container 
      docker_container:
              name: httpd
              image: httpd 
              state: started
              exposed_ports:
              - "80"
              ports:
              - "8888:80"

