---
# tasks file for build_images

  - name: copying file with playbook
    become: true
    copy:
        src: /home/ramoukha/cloud-1/roles/files
        dest: /home/ubuntu
        mode: 0644

  - name: build mariadb image
    docker_image:
      name: mariadb
      build:
        path: /home/ubuntu/files/mariadb
      source: build

  - name: build mysql image
    docker_image:
      name: mysql
      build:
        path: /home/ubuntu/files/mysql
      source: build


  - name: build wordpress image
    docker_image:
     name: my-wordpress
     build:
        path: /home/ubuntu/files/wordpress
     source: build
